name = "PolynomialRings"
uuid = "c8ed2632-8d42-5af4-9089-7afd55769a28"
authors = ["Timo Kluck <tkluck@infty.nl>"]
version = "0.7.4"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InPlace = "12a7aed9-f4ee-5e21-a57e-4f63a8148421"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
Combinatorics = "1.0"
DataStructures = "0.17, 0.18"
InPlace = "0.3"
OrderedCollections = "1.1"
ProgressMeter = "1.2"
Transducers = "0.4.39"
julia = "1.6"
